# Generated by Django 3.2.25 on 2025-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_notification_profile_savingsgoal_tag_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tracker.Tag'),
        ),
    ]
